{% set name = "HydroErr" %}
{% set version = "1.24" %}
{% set sha256 = "8fc3e3f38517cb6b6113ace4f99a153a34a4324ca2444cfd036c25767c6ce8f7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  

requirements:
  host:
    - pip
    - python
  run:
    - python
    - numpy
    - scipy

test:
  imports:
    - HydroErr
    - HydroErr.HydroErr

about:
  home: https://github.com/BYU-Hydroinformatics/HydroErr
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'Goodness of fit metrics for use in comparison studies'
  description: Goodness of fit metrics for use in comparison studies, specifically for use in the field of hydrology
  doc_url: https://byu-hydroinformatics.github.io/HydroErr/
  dev_url: https://github.com/BYU-Hydroinformatics/HydroErr
  
extra:
  recipe-maintainers:
    - waderoberts123
