{% set name = "HydroErr" %}
{% set version = "1.24" %}
{% set sha256 = "8fc3e3f38517cb6b6113ace4f99a153a34a4324ca2444cfd036c25767c6ce8f7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - wheel
  run:
    - python >={{ python_min }}
    - numpy >=2.0,<3.0
    - scipy >=1.0,<2.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - HydroErr
    - HydroErr.HydroErr

about:
  home: https://github.com/BYU-Hydroinformatics/HydroErr
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'Goodness of fit metrics for use in comparison studies'
  description: Goodness of fit metrics for use in comparison studies, specifically for use in the field of hydrology
  doc_url: https://byu-hydroinformatics.github.io/HydroErr/
  dev_url: https://github.com/BYU-Hydroinformatics/HydroErr

extra:
  recipe-maintainers:
    - pythonweb2
