travis:
  secure:
    BINSTAR_TOKEN: Kaz4I46c7yRNGxupV+51b+31AmqLRMORc+6o5Lzup9nRBvXhX0ZSrYWs4FAiIH9q7mBXuNlHuKrAsMvOiuuyITW7B+MD9ThzqVb8cNrre+sLdxjnAxXDYSNBGJSQIbEfNj27kQvnOmXotLJAqR8Gnkw7QizrBOIph8GjcJLrp4lAiFvjJ3CYg5fI3btd1StebYsi7vwvCG0/XPkC0qejzJVNC3yyd4lSs7oYvcMys3+WrRr8KnFPpv0vln235OujnW0f03aSoFKTVv0Ift9oUko6wHxq3qdSwitATybipcCjwLXPrGImdPeGhkgLsBLr/L2xMKuMMc3MejgcKG5oZfJsEy0W8Ajqx/A4AraF7rQuzryJmkResHtcFeHgGsN/1v4TTTlMHgZQT7MQRx6ThGkCPuQAGsS+d+8REkp+HBL8p0nxh1s5pzHjw73J2LVTFXtKa/YAvkZe7o48thyNbjsMISwrgSeXy5flYvo1KqaqTo2x/b0r8zXyHonP/wT+6TXvyP9/UXEfblTE4mx+OLI0qpf95fnynL6sFLSVzWBMjDzroV3tt28sWouY2YMcFai9w6/ULak9G2khXvLxx22O7WwVvBOWVJckgBuqfuOEFRBu1fshu/3YApmb2kDPNRQYWEWhIftQ3Q7TT6on+6DGVUtKgvjvIxmeXSn6dsU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
