travis:
  secure:
    BINSTAR_TOKEN: H+xlGj69aYrC6QuWwDXOFwbZB57HVbfdSEq4txxhI/bckMpt3VERlQg6E5msAtR660YzOjw5lMNlGGVKZjDIgU6KB00zs1b1DPf+IVr6sVqukX4QuKNgLR4m4Yq7jZFqusJ9hb6Ry3eCj03I9FR9ED/qh0+JXgjSDDho4BjnmmPDT/gnawSav6cQ131Vu4y5VHXorcw4lSg0K/fjEpW47OvjdaotGF8YMg+RMwhnuGIkk1k85/Yzk8Xc1RFPdK50y/7DwgLQi317DC+TrdS8GLQvob6jKcRpRbgnTuCGRAm4IwmLu0rEpR6Siecs5zd/b6PEP4VprKDgP/30aIPD68nNHMUHljMb+g62TOPPTowyDQp8i7ow5R4Ffd/y/iO0t8N1glhqG2r44zJNWvMGOina6bRwR4CUVBwoI1mJy6pP5MuwcuHJYbJwrnIZxnoUu2RhlpVn4fhE/zohqm+Qv3y+65jkXff6AokDXZa4fA5WpnYjsKucK0wTITfu9E04I20Xk6PoThjXKbJwSo7nWLKCtTLemLT9nbq59FfEYz/RMW68FlOIDRH0eGK2lnKDgA7U4RMm5q8SPyIItlyZPmLGUsdC6CRijeJW2UXVkwDZ0CZgndBsgang8EPIGOo0ka2XgL5dYCOEPyaJsnM9ABAHdccbx6ONmVnF69ctFxg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
